### PR TITLE
hoc and loc

### LINKED ISSUE #31: hoc and loc badges

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #31 

---

## PR-Codex overview
This PR adds badges for code metrics and licensing information to the README file.

### Detailed summary
- Added a "Hits-of-Code" badge from Hits-of-Code website.
- Added a "Lines-of-Code" badge from Tokei.rs.
- Added a "PDD status" badge from 0pdd.com.
- Added a "License" badge indicating the project is licensed under MIT.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-07-29T07:09:22.441102``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
